name: Main CICD Pipeline
run-name: Main CICD Pipeline
on: [push]
jobs:
  Main-CICD-Pipeline:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting Main CICD Pipeline for ${{ github.ref }}..."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build & Test
        run: |
          ls ./build-all.sh
      - run: echo "Status is ${{ job.status }}."
