name: Main CICD Pipeline
on: [push]
jobs:
  main-cicd-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build & Test
        run: ./build-all.sh
      - run: echo "Status is ${{ job.status }}."
